name: Github Pages Deploy

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install and build
        run: npm install && npm run build:github && cp ./dist/json-placeholder-posts/index.html ./dist/json-placeholder-posts/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: master
          folder: dist/json-placeholder-posts

permissions: write-all
