name: Github Pages Deploy

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.x

      - name: Install and build
        working-directory: ./json_placeholder_posts
        run: npm install && npm run build:github && cp dist/json_placeholder_posts/index.html dist/json_placeholder_posts/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.x
        with:
          branch: master
          folder: json_placeholder_posts/dist/json_placeholder_posts
